package com.thom9521.mario;

public enum MarioType {
    PLAYER, COIN, PLATFORM, DOOR, ENEMY, DANGER, DOOR2, DOOR3, DANGER2, DOOR4, SHELL, ENEMY3, HEART, CHEST,
    DOOR5, DANGER3, GIRL, FIREBALL, SHELL2, BOWSER
}
